### ISSUE TITLE
Loading version of nvm

### ISSUE THREAD

**Issue by artivilla99** [holman/dotfiles#215]
So I'm not 100% I'm doing this correctly, but I'm trying to setup up node, nvm, npm and got .nvm installed  in $HOME using homebrew. But this entire directory needs to be in .dotfiles?

I also need .nvmrc to load the latest version of nvm installed so the two commands I need to run are as follows:
nvm install v4.2.1
nvm use v4.2.1

Where would you include this and does this go in your .localrc file or inside node/.nvmrc?

**Comment by holman** [comment]
This sounds similar to how the `atom.symlink` directory is set up in the current project. Any directory that ends in `.symlink` will get symlinked to your home directory once you run `script/bootstrap`. So you can do that manually, or just move your `.nvm` directory to your dotfiles and run `script/bootstrap`.

It could be I've misinterpreted your request, because I haven't used JavaScript in thirty six years and can't remember how that gets set up.

As far as the `.nvmrc`, you might be able to get by with tossing those commands in a file called, say, `nvm.symlink/nvm.zsh`. Then when your environment starts up it'll run those commands for ya.

Let me know if that helps!

**Comment by artivilla99** [comment]
Hi!

Sorry it took me a while to get back. The beauty of asynchronous communication :+1: You understood it correct and it worked super smooth! So thank you. Haha. You mean thirty years :/

**Comment by rblakeley** [comment]
@artivilla hey, since you used Homebrew, did you end up having a file like this?

#### `nvm/nvm.zsh`:

```
# Node and npm Version Manager
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

**Comment by jacobwgillespie** [comment]
@rblakeley that's essentially [what I've got](https://github.com/jacobwgillespie/dotfiles/blob/master/node/nvm.zsh):

```zsh
export NVM_DIR=~/.nvm
if [ -e "$(brew --prefix nvm)/nvm.sh" ]; then
  source $(brew --prefix nvm)/nvm.sh
fi
```

**Comment by rblakeley** [comment]
@jacobwgillespie 👍 thanks!
