### ISSUE TITLE
Track ~/.ssh/config

### ISSUE THREAD

**Issue by alxppp** [holman/dotfiles#276]
Is there a way to check in just the ~/.ssh/config file without creating a ssh.symlink directory? Otherwise the ssh keys and known_hosts would be tracked by git. And creating a .gitignore for these doesn't look like the best way to do it.

**Comment by holman** [comment]
I think .gitignore is probbbbbbably the best way to do it. I just have that outside of my dotfiles directory because... well, no reason, just laziness and haven't seen a huge need yet, I suppose. :)

Going to close this for now but if any other thoughts I'd be happy to hear them!

**Comment by alxppp** [comment]
I'm putting the `ln -s` in an install.sh for now.

How about creating a special character (like `\`) that is replaced with `/` for `.symlink` files, so we can specify subdirectories? The ssh config file would then be in `~/dotfiles/ssh/ssh\config.symlink`.

**Comment by jacobwgillespie** [comment]
You could always whitelist that file in your `.gitignore` by adding the following to it:

```
ssh.symlink/*
!ssh.symlink/config
```

That would block everything but the config file, so any SSH keys, etc, would be omitted.

> How about creating a special character (like `\`) that is replaced with `/`

It'd probably be better for it to just detect `.symlink` files or folders at any depth and preserve their hierarchy when symlinking rather than introducing the backslash as a separator.  But with the `.gitignore` adjustments above you can avoid it the extra complexity entirely.
